name: Setup

inputs:
  ssh-private-key:
    description: SSH Private Key
    required: true

outputs:
  kamal-registry-password:
    description: Kamal Registry Password
    value: ${{ steps.auth.outputs.access_token }}

runs:
  using: composite
  steps:
    - uses: ruby/setup-ruby@v1
      env:
        BUNDLE_GEMFILE: ./Gemfile
      with:
        ruby-version: .ruby-version
        bundler-cache: true

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ inputs.ssh-private-key }}
