name: 02. Deploy Manually

permissions:
  id-token: write
  contents: read

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment"
        required: true
        default: "production"
        type: choice
        options:
          - production

jobs:
  build-production:
    name: build-deploy-production
    if: ${{ github.event.inputs.environment == 'production' }}
    concurrency:
      group: production_environment
      cancel-in-progress: true
    environment:
      name: production
      url: https://app.onetribe.team
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v5
        with:
          ref: ${{ github.event.workflow_run.head_branch }}

      - name: Setup
        uses: ./.github/workflows/setup
        id: pre-build
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Kamal Deploy
        uses: igor-alexandrov/kamal-deploy@v0.4.1
        with:
          registry-username: ${{ secrets.DIGITAL_OCEAN_ACCESS_TOKEN }}
          registry-password: ${{ secrets.DIGITAL_OCEAN_ACCESS_TOKEN }}
          environment: production
        env:
          RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
