name: _lint

on:
  workflow_call:
  schedule:
    - cron: "0 3 * * 1" # Every monday at 3 AM

jobs:
  rubocop:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - uses: actions/checkout@v5

    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: .ruby-version
        bundler-cache: true

    - name: RuboCop
      run: bin/rubocop -A

  brakeman:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5

    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: .ruby-version
        bundler-cache: true

    - name: Scan
      run: bin/brakeman -z -A -q --ensure-latest --no-pager

  erb-lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5

    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: .ruby-version
        bundler-cache: true
    - name: ERB Lint
      run: bin/erb_lint ./app/**/*.erb

    # Advanced Security must be enabled for this repository to use code scanning.
    # Need to enable GitHub Advanced Security

    #- name: Scan
    #  continue-on-error: true
    #  run: |
    #    bundle exec brakeman -z -A -q --ensure-latest --no-pager -f sarif -o output.sarif.json .

    #- name: Upload SARIF
    #  uses: github/codeql-action/upload-sarif@v1
    #  with:
    #    sarif_file: output.sarif.json
